# Generated by Django 2.0.5 on 2018-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordnum', models.IntegerField(blank=True, db_column='RecordNum', null=True)),
                ('vertag', models.CharField(blank=True, db_column='VerTag', max_length=25, null=True)),
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=25, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
