# Generated by Django 2.0.5 on 2018-05-12 15:18
# comment

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordnum', models.IntegerField(blank=True, db_column='RecordNum', null=True)),
                ('vertag', models.CharField(blank=True, db_column='VerTag', max_length=25, null=True)),
                ('hostname', models.CharField(blank=True, db_column='HostName', max_length=25, null=True)),
                ('pdb', models.CharField(blank=True, db_column='PDB', max_length=25, null=True)),
                ('dir', models.CharField(blank=True, db_column='DIR', max_length=25, null=True)),
                ('osuser', models.CharField(blank=True, db_column='OSUser', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'db_table': 'deploys',
                'managed': False,
            },
        ),
    ]
